// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.Active.Infrastructure.Persistence;

#nullable disable

namespace Voting.Active.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.Active.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElectionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("elections", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingPlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingTerminalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.HasIndex("VotingPlaceId");

                    b.HasIndex("VotingTableId");

                    b.HasIndex("VotingTerminalId");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.HasIndex("ElectionId");

                    b.ToTable("voters", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("voting_places", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VotingPlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VotingPlaceId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingPlaceId");

                    b.HasIndex("VotingPlaceId1");

                    b.ToTable("voting_tables", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingTerminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VotingTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VotingTableId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingTableId");

                    b.HasIndex("VotingTableId1");

                    b.ToTable("voting_terminals", (string)null);
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("Voting.Active.Domain.Entities.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Vote", b =>
                {
                    b.HasOne("Voting.Active.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.VotingPlace", "VotingPlace")
                        .WithMany()
                        .HasForeignKey("VotingPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.VotingTable", "VotingTable")
                        .WithMany()
                        .HasForeignKey("VotingTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.VotingTerminal", "VotingTerminal")
                        .WithMany()
                        .HasForeignKey("VotingTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Voter");

                    b.Navigation("VotingPlace");

                    b.Navigation("VotingTable");

                    b.Navigation("VotingTerminal");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.Voter", b =>
                {
                    b.HasOne("Voting.Active.Domain.Entities.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingTable", b =>
                {
                    b.HasOne("Voting.Active.Domain.Entities.VotingPlace", "VotingPlace")
                        .WithMany()
                        .HasForeignKey("VotingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.VotingPlace", null)
                        .WithMany("VotingTables")
                        .HasForeignKey("VotingPlaceId1");

                    b.Navigation("VotingPlace");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingTerminal", b =>
                {
                    b.HasOne("Voting.Active.Domain.Entities.VotingTable", "VotingTable")
                        .WithMany()
                        .HasForeignKey("VotingTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voting.Active.Domain.Entities.VotingTable", null)
                        .WithMany("VotingTerminals")
                        .HasForeignKey("VotingTableId1");

                    b.Navigation("VotingTable");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingPlace", b =>
                {
                    b.Navigation("VotingTables");
                });

            modelBuilder.Entity("Voting.Active.Domain.Entities.VotingTable", b =>
                {
                    b.Navigation("VotingTerminals");
                });
#pragma warning restore 612, 618
        }
    }
}
